import cloth from "../../public/cloth.png";
import spark from "../../public/spark.png";
import gpt3 from "../../public/gpt3.png";
import bank from "../../public/hsfinancial.png";
import metrix from "../../public/metrix.png";
const projectData = [
  {
    id: 1,
    title: "CRUD Email Submission",
    description:
      "CRUD Email Submission is a dynamic web application designed to streamline the process of collecting and managing user emails. With a user-friendly interface, it allows visitors to submit their email addresses, which are then securely stored in a database. The application also provides administrators with the ability to perform CRUD operations, enabling efficient management of the submitted emails for future communication or analysis.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic: "https://rb.gy/9jh39",
    projectLink: "https://rb.gy/9jh39",
    ghRepo: "https://rb.gy/9jh39",
  },
  {
    id: 2,
    title: "Agency Design & Implement",
    description:
      "Spark Social's redesign is a visually stunning website project showcasing my expertise in user experience design and implementation. Leveraging the Duda platform, I crafted a seamless and intuitive user interface, prioritizing functionality and aesthetics to deliver an engaging user experience. This project demonstrates my versatility in working with different platforms and highlights my ability to create impactful designs that elevate a brand's online presence.",
    skills: ["ZTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic: "https://rb.gy/9jh39",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
  {
    id: 3,
    title: "Responsive GPT3 Site",
    description:
      "Responsive GPT3 Site is a dynamic web application I built as part of my Software Engineering portfolio. Leveraging the power of JavaScript, React, and CSS, this project showcases the capabilities of OpenAI's GPT-3.5 language model by creating an interactive and adaptive website. Users can engage in natural language conversations with the site, receiving intelligent responses generated by GPT-3.5, while the responsive design ensures an optimal viewing experience across various devices.",
    skills: ["KTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic: "https://rb.gy/9jh39",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
  {
    id: 4,
    title: "Banking Application",
    description:
      "The Banking App project is a fully functional web application developed using JavaScript, React, HTML, and CSS. It offers a secure login system to store user credentials and provides a user-friendly interface for performing basic banking operations such as balance inquiries, fund transfers, and transaction history tracking. This project showcases my skills in front-end development and demonstrates my ability to create robust and interactive applications.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic: "https://rb.gy/9jh39",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
  {
    id: 5,
    title: "Social Media Metrics App",
    description:
      "The Social Media Metrics App is a powerful tool designed to provide users with comprehensive analytics and insights into their social media performance. With real-time data tracking and visualizations, it offers a user-friendly interface for monitoring key metrics such as engagement, follower growth, and post reach across multiple platforms. This project showcases my ability to develop data-driven applications that empower individuals and businesses to optimize their social media strategies for maximum impact.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic: "https://rb.gy/9jh39",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
];

export default projectData;
